# Generated by Django 6.0 on 2025-12-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetrack',
            name='spotify_id',
        ),
    ]
